export const API_GAME_SETTINGS_REQUEST = "API_GAME_SETTINGS_REQUEST";
export const API_GAME_SETTINGS_SUCCESS = "API_GAME_SETTINGS_SUCCESS";
export const API_GAME_SETTINGS_FAILURE = "API_GAME_SETTINGS_FAILURE";

export const API_GAME_WINNER_REQUEST = "API_GAME_WINNER_REQUEST";
export const API_GAME_WINNER_SUCCESS = "API_GAME_WINNER_SUCCESS";
export const API_GAME_WINNER_FAILURE = "API_GAME_WINNER_FAILURE";

export const API_LEADERS_REQUEST = "API_LEADERS_REQUEST";
export const API_LEADERS_SUCCESS = "API_LEADERS_SUCCESS";
export const API_LEADERS_FAILURE = "API_LEADERS_FAILURE";

export const APP_GAME_START = "APP_GAME_START";
